import '@/app/globals.css';
import {SessionProvider} from "next-auth/react";
import {auth} from "@/auth";
import React from "react";
import {Toaster} from "@/components/ui/sonner";

export const metadata = {
    title: 'OneTeam',
    description: 'Generated by Next.js',
}

export default async function RootLayout({children}:
{ children: React.ReactNode }) {
    const session = await auth();

    return (
        <SessionProvider session={session}>
            <html lang="en">
            <body>
            <Toaster/>
            {children}
            </body>
            </html>
        </SessionProvider>
    )
}
